### ISSUE TITLE
Cannot build Intel Implicit SPMD Program Compiler: CMake Error at cmake/LLVMConfig.cmake:   Failed running

### ISSUE THREAD

**Issue by kevinsmia1939** [flathub/org.freedesktop.Sdk.Extension.llvm11#10]
Hello,

I tried to build Intel® Implicit SPMD Program Compiler (ISPC) but failed.
https://github.com/ispc/ispc

Not really sure what happen, maybe something not compatible with LLVM bundled in the Sdk?

flatpak-builder 1.0.12
```
-- Detected LLVM version: 11.1.0
CMake Warning at cmake/LLVMConfig.cmake:134 (message):
  LLVM was built without assertions enabled (-DLLVM_ENABLE_ASSERTIONS=OFF).
  This disables dumps, which are required for ISPC to be fully functional.
Call Stack (most recent call first):
  CMakeLists.txt:174 (include)


-- GIT_BINARY: /usr/bin/git
-- M4 macro processor: /usr/bin/m4
-- Found Python3: /usr/bin/python3.8 (found version "3.8.8") found components: Interpreter 
-- Found BISON: /usr/bin/bison (found suitable version "3.6.4", minimum required is "3.0") 
-- Found FLEX: /usr/bin/flex (found suitable version "2.6.4", minimum required is "2.6") 
llvm-config: unknown component name: arm
CMake Error at cmake/LLVMConfig.cmake:119 (message):
  Failed running
  /usr/lib/sdk/llvm11/bin/llvm-config;--libfiles;engine;ipo;bitreader;bitwriter;instrumentation;linker;option;frontendopenmp;x86;arm;aarch64
Call Stack (most recent call first):
  cmake/LLVMConfig.cmake:156 (run_llvm_config)
  CMakeLists.txt:271 (get_llvm_libfiles)


-- Configuring incomplete, errors occurred!
```

Minimal flatpak manifest that produce this error.
```
app-id: com.github.ispc.ISPC
runtime: org.freedesktop.Platform
sdk: org.freedesktop.Sdk
runtime-version: '20.08'
sdk-extensions : org.freedesktop.Sdk.Extension.llvm11
command: ISPC
finish-args:
  - --share=ipc
  - --socket=wayland
  - --socket=fallback-x11
  - --device=dri

modules:
  - name: ISPC
    buildsystem: cmake
    build-options:
      - prepend-path: "/usr/lib/sdk/llvm11/bin"
      - prepend-ld-library-path: "/usr/lib/sdk/llvm11/lib"
    config-opts:
      - -DLLVM_DIR=/usr/lib/sdk/llvm11/lib/cmake/llvm
      - -DCMAKE_BUILD_TYPE:STRING=Release
      - -DISPC_INCLUDE_EXAMPLES:BOOL=OFF
      - -DISPC_NO_DUMPS:BOOL=ON
      - -DCMAKE_INSTALL_PREFIX=/app
    sources:
      - type: git
        url: https://github.com/ispc/ispc
        tag: v1.15.0
```
