### ISSUE TITLE
Why -DBUILD_SHARED_LIBS:BOOL=OFF and *.a in cleanup?

### ISSUE THREAD

**Issue by kevinsmia1939** [flathub/org.freedesktop.Sdk.Extension.llvm11#2]
Hello,

So I was trying to build CastXML, it needed clang. I think this extension might provide it, but still fail.

```
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/clang/ClangTargets.cmake:356 (message):
  The imported target "clangBasic" references the file

     "/usr/lib/x86_64-linux-gnu/libclangBasic.a"
```

I think that because -DBUILD_SHARED_LIBS:BOOL=OFF flag was use to generate static libs (.a) but was delete during cleanup.

```
      "cleanup": [
        "/include/lld",
        "*.a",
        "*.a.syms"
      ],
```

I think it should be -DBUILD_SHARED_LIBS:BOOL=ON?

**Comment by Erick555** [comment]
LLVM upstream [recommends](https://llvm.org/docs/CMake.html#llvm-specific-variables) using `-DLLVM_BUILD_LLVM_DYLIB` instead of `-DBUILD_SHARED_LIBS`:

> BUILD_SHARED_LIBS is only recommended for use by LLVM developers. If you want to build LLVM as a shared library, you should use the LLVM_BUILD_LLVM_DYLIB option.

Not cleaning .a files is possible but it will raise extension size significantly.

**Comment by kevinsmia1939** [comment]
@Erick555

Hi

Thanks for input. The reason I ask this is because I suspect my failing CastXML build is relate to this.
Do you know if it does or how to fix it?

Try building this with
`flatpak-builder --install --user build com.githuh.CastXML.CastXML.yaml`
```
app-id: com.githuh.CastXML.CastXML
runtime: org.freedesktop.Platform
sdk: org.freedesktop.Sdk
runtime-version: '20.08'
sdk-extensions:
  - org.freedesktop.Sdk.Extension.llvm11
command: castxml

modules:
  - llvm.yaml
  - name: castxml
    buildsystem: cmake
    config-opts:
      - -DCLANG_LINK_CLANG_DYLIB:BOOL=ON
    build-options:
      env:
        CC: clang
        CXX: clang++
    sources:
      - type: archive
        url: https://github.com/CastXML/CastXML/archive/v0.4.3.tar.gz
        sha256: 3dd94096e07ffe103b2a951e4ff0f9486cc615b3ef08e95e5778eaaec667fb65
```

**Comment by Erick555** [comment]
I don't know if `clangBasic` shared/dylib variant exist. If not then restoring static libs is the only option for this app.

**Comment by Erick555** [comment]
This [build](https://github.com/flathub/org.freedesktop.Sdk.Extension.llvm11/pull/3#issuecomment-793136138) should fix your issue as it contains missing clangBasic.a library. The cost is additional ~450MB. It's not small but maybe having fully functional llvm is worth it.

Note that you have to set up proper prefixes in order to use extensions otherwise you would end up using llvm from runtime which doesn't include static libs. 

Add below to `build-options`:

```
prepend-path: /usr/lib/sdk/llvm11/bin
prepend-ld-library-path /usr/lib/sdk/llvm11/lib
```

**Comment by kevinsmia1939** [comment]
@Erick555

Did I do it right? I still could not build CastXML.

```
app-id: com.github.CastXML.CastXML
runtime: org.freedesktop.Platform
sdk: org.freedesktop.Sdk
runtime-version: '20.08'
sdk-extensions:
  - org.freedesktop.Sdk.Extension.llvm11
command: castxml

modules:
  - name: castxml
    buildsystem: cmake
    config-opts:
      - -DCLANG_LINK_CLANG_DYLIB:BOOL=ON
    build-options:
      env:
        CC: clang
        CXX: clang++
        prepend-path: /usr/lib/sdk/llvm11/bin
        prepend-ld-library-path: /usr/lib/sdk/llvm11/lib
    sources:
      - type: archive
        url: https://github.com/CastXML/CastXML/archive/v0.4.3.tar.gz
        sha256: 3dd94096e07ffe103b2a951e4ff0f9486cc615b3ef08e95e5778eaaec667fb65
```

```
kev@localhost:~/Desktop/Software/castxml> flatpak install --user https://dl.flathub.org/build-repo/39767/org.freedesktop.Sdk.Extension.llvm11.flatpakref


        ID                                               Branch            Op            Remote                   Download
 1. [✓] org.freedesktop.Sdk.Extension.llvm11             20.08             i             llvm11-origin            325.0 MB / 326.6 MB

Installation complete.
kev@localhost:~/Desktop/Software/castxml> flatpak-builder --install --user build castxml.yaml --force-clean
Downloading sources
Initializing build dir
Committing stage init to cache
Starting build of com.github.CastXML.CastXML
========================================================================
Building module castxml in /home/kev/Desktop/Software/castxml/.flatpak-builder/build/castxml-1
========================================================================
-- The C compiler identification is Clang 10.0.1
-- The CXX compiler identification is Clang 10.0.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/clang/ClangTargets.cmake:356 (message):
  The imported target "clangBasic" references the file

     "/usr/lib/x86_64-linux-gnu/libclangBasic.a"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/lib/x86_64-linux-gnu/cmake/clang/ClangTargets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/clang/ClangConfig.cmake:19 (include)
  CMakeLists.txt:75 (find_package)


-- Configuring incomplete, errors occurred!
See also "/run/build/castxml/CMakeFiles/CMakeOutput.log".
Error: module castxml: Child process exited with code 1

```

```
Name                                                   Application ID                                      Version            Branch            Origin                    Installation
Tor Browser Launcher                                   com.github.micahflee.torbrowser-launcher            0.3.3              stable            flathub                   user
Blender                                                org.blender.Blender                                 2.92               stable            flathub                   user
Codecs                                                 org.blender.Blender.Codecs                                             stable            flathub                   user
Codelite                                               org.codelite.Codelite                                                  master            codelite-origin           user
darktable                                              org.darktable.Darktable                             3.4.1              stable            flathub                   user
FreeCAD                                                org.freecadweb.FreeCAD                              0.18.5             stable            flathub                   user
Freedesktop Platform                                   org.freedesktop.Platform                            20.08.6            20.08             flathub                   system
Freedesktop Platform                                   org.freedesktop.Platform                            20.08.6            20.08             flathub                   user
default                                                org.freedesktop.Platform.GL.default                                    20.08             flathub                   system
default                                                org.freedesktop.Platform.GL.default                                    20.08             flathub                   user
Intel                                                  org.freedesktop.Platform.VAAPI.Intel                                   20.08             flathub                   system
Intel                                                  org.freedesktop.Platform.VAAPI.Intel                                   20.08             flathub                   user
ffmpeg-full                                            org.freedesktop.Platform.ffmpeg-full                                   20.08             flathub                   user
openh264                                               org.freedesktop.Platform.openh264                   2.1.0              2.0               flathub                   system
openh264                                               org.freedesktop.Platform.openh264                   2.1.0              2.0               flathub                   user
Freedesktop SDK                                        org.freedesktop.Sdk                                 20.08.6            20.08             flathub                   system
LLVM 11                                                org.freedesktop.Sdk.Extension.llvm11                11.0.1             20.08             llvm11-origin             user
GNU Image Manipulation Program                         org.gimp.GIMP                                       2.99.4             beta              flathub-beta              system
GNOME Application Platform version 3.38                org.gnome.Platform                                                     3.38              flathub                   system
GNOME Application Platform version 3.38                org.gnome.Platform                                                     3.38              flathub                   user
GNOME Software Development Kit version 3.38            org.gnome.Sdk                                                          3.38              flathub                   user
Adwaita dark GTK theme                                 org.gtk.Gtk3theme.Adwaita-dark                                         3.22              flathub                   user
Breeze Gtk theme                                       org.gtk.Gtk3theme.Breeze-Dark                                          3.22              flathub                   system
Breeze Gtk theme                                       org.gtk.Gtk3theme.Breeze-Dark                                          3.22              flathub                   user
KDE Application Platform                               org.kde.Platform                                                       5.15              flathub                   system
KDE Software Development Kit                           org.kde.Sdk                                                            5.15              flathub                   system
OpenTTD                                                org.openttd.OpenTTD                                 1.10.3             stable            flathub                   user
kev@localhost:~/Desktop/Software/castxml> 
```

**Comment by Erick555** [comment]
The file is at `/usr/lib/sdk/llvm11/lib/libclangBasic.a` maybe you need to pass something to cmake in order to find it.

**Comment by Erick555** [comment]
> -- The C compiler identification is Clang 10.0.1
> -- The CXX compiler identification is Clang 10.0.1

@kevinsmia1939  It doesn't use extension at all maybe try adding below in `config-opts`:

`-DLLVM_DIR=/usr/lib/sdk/llvm11/lib/cmake/llvm`
or 
`-DClang_DIR=/usr/lib/sdk/llvm11/lib/cmake/clang`

or both.

It was [reported to help in similar case](https://github.com/CastXML/CastXML/issues/148).

**Comment by Erick555** [comment]
@kevinsmia1939 actually you may set `-DCLANG_LINK_CLANG_DYLIB` and then you don't even need static libs or this extension.

**Comment by kevinsmia1939** [comment]
> @kevinsmia1939 actually you may set `-DCLANG_LINK_CLANG_DYLIB` and then you don't even need static libs or this extension.

I do have that flag turned on, but still cause same issue.

I set -DLLVM_DIR=/usr/lib/sdk/llvm11/lib/cmake/llvm and CastXML build fine now. Thanks.

```
  - name: castxml
    buildsystem: cmake
    config-opts:
      - -DCLANG_LINK_CLANG_DYLIB:BOOL=ON
      - -DLLVM_DIR=/usr/lib/sdk/llvm11/lib/cmake/llvm
    build-options:
      env:
        CC: clang
        CXX: clang++
        prepend-path: /usr/lib/sdk/llvm11/bin
        prepend-ld-library-path: /usr/lib/sdk/llvm11/lib
    sources:
      - type: archive
        url: https://github.com/CastXML/CastXML/archive/v0.4.3.tar.gz
        sha256: 3dd94096e07ffe103b2a951e4ff0f9486cc615b3ef08e95e5778eaaec667fb65 
```
